name = "RCMreorder"
uuid = "01d865ed-7517-49ba-9db7-d3177711ef4b"
authors = ["BIAN, Peiliang <47040923+bplcn@users.noreply.github.com>"]
version = "0.1.0"

[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
